// Generated by https://quicktype.io

export interface LoanResponse {
    encodedKey:                      string;
    id:                              string;
    accountHolderType:               string;
    accountHolderKey:                string;
    creationDate:                    string;
    approvedDate?:                   string;
    lastModifiedDate:                string;
    activationTransactionKey?:       string;
    lastAccountAppraisalDate?:       string;
    accountState:                    AccountState;
    productTypeKey:                  string;
    loanName:                        string;
    loanAmount:                      number;
    paymentMethod:                   string;
    accruedInterest:                 number;
    interestFromArrearsAccrued?:     number;
    lastInterestAppliedDate?:        string;
    accruedPenalty:                  number;
    allowOffset:                     boolean;
    arrearsTolerancePeriod:          number;
    accountArrearsSettings:          AccountArrearsSettings;
    latePaymentsRecalculationMethod: string;
    balances:                        { [key: string]: number };
    disbursementDetails:             DisbursementDetails;
    prepaymentSettings:              any;
    penaltySettings:                 PenaltySettings;
    scheduleSettings:                ScheduleSettings;
    interestSettings:                InterestSettings;
    assets:                          any[];
    guarantors:                      any[];
    fundingSources:                  any[];
    tranches:                        any[];
    futurePaymentsAcceptance:        string;
    currency:                        Currency;
    plannedInstallmentFees:          any[];
    _Informacion_Adicional:          InformacionAdicional;
}

export interface InformacionAdicional {
    Codigo_Promotor: string;
}

export interface AccountArrearsSettings {
    encodedKey:                                string;
    toleranceCalculationMethod:                string;
    dateCalculationMethod:                     string;
    nonWorkingDaysMethod:                      string;
    toleranceFloorAmount:                      number;
    tolerancePeriod:                           number;
    tolerancePercentageOfOutstandingPrincipal: number;
}

export enum AccountState {
    Active = "ACTIVE",
    Approved = "APPROVED",
    PendingApproval = "PENDING_APPROVAL",
}

export interface Currency {
    currencyCode: Code;
    code:         Code;
}

export enum Code {
    Cop = "COP",
}

export interface DisbursementDetails {
    encodedKey:               string;
    expectedDisbursementDate: string;
    disbursementDate?:        string;
    firstRepaymentDate:       string;
    transactionDetails:       TransactionDetails;
    fees:                     any[];
}

export interface TransactionDetails {
    encodedKey:            string;
    transactionChannelKey: string;
    transactionChannelId:  string;
    internalTransfer:      boolean;
}

export interface InterestSettings {
    interestRateSource:               string;
    accrueInterestAfterMaturity:      boolean;
    interestApplicationMethod:        string;
    interestBalanceCalculationMethod: string;
    interestCalculationMethod:        string;
    interestChargeFrequency:          string;
    interestRate:                     number;
    interestType:                     string;
    accrueLateInterest:               boolean;
}

export interface PenaltySettings {
    loanPenaltyCalculationMethod: string;
    penaltyRate:                  number;
}

export interface ScheduleSettings {
    hasCustomSchedule:                  boolean;
    defaultFirstRepaymentDueDateOffset: number;
    principalRepaymentInterval:         number;
    gracePeriod:                        number;
    gracePeriodType:                    string;
    repaymentInstallments:              number;
    repaymentPeriodCount:               number;
    scheduleDueDatesMethod:             string;
    periodicPayment:                    number;
    repaymentPeriodUnit:                string;
    repaymentScheduleMethod:            string;
    paymentPlan:                        any[];
}


