export {Address} from './address.dto'
export {Attachment} from './attachment.dto'
export {CreateClientDto} from './create-client.dto'
export {IDDocument} from './idDocument.dto'
export {_Personalizados} from './_personalizados.dto'
export {Pep} from './pep.dto'