// Generated by https://quicktype.io

export interface DepositResponse {
    accountHolderKey:          string;
    accountHolderType:         string;
    accountType:               string;
    accruedAmounts:            any;
    assignedBranchKey:         string;
    assignedCentreKey:         string;
    assignedUserKey:           string;
    balances:                  any;
    creditArrangementKey:      string;
    currencyCode:              string;
    id:                        string;
    interestSettings:          InterestSettings;
    internalControls:          InternalControls;
    name:                      string;
    notes:                     string;
    overdraftInterestSettings: OverdraftInterestSettings;
    overdraftSettings:         OverdraftSettings;
    productTypeKey:            string;
    withholdingTaxSourceKey:   string;
}

export interface InterestSettings {
    interestPaymentSettings: InterestPaymentSettings;
    interestRateSettings:    InterestRateSettings;
}

export interface InterestPaymentSettings {
    interestPaymentDates: InterestPaymentDate[];
    interestPaymentPoint: string;
}

export interface InterestPaymentDate {
    day:   number;
    month: number;
}

export interface InterestRateSettings {
    interestChargeFrequency:      string;
    interestChargeFrequencyCount: number;
    interestRate:                 number;
    interestRateReviewCount:      number;
    interestRateReviewUnit:       string;
    interestRateTerms:            string;
    interestRateTiers:            InterestRateTier[];
    interestSpread:               number;
}

export interface InterestRateTier {
    endingBalance: number;
    endingDay:     number;
    interestRate:  number;
}

export interface InternalControls {
    maxDepositBalance:        number;
    maxWithdrawalAmount:      number;
    recommendedDepositAmount: number;
    targetAmount:             number;
}

export interface OverdraftInterestSettings {
    interestRateSettings: InterestRateSettings;
}

export interface OverdraftSettings {
    allowOverdraft:      boolean;
    overdraftExpiryDate: string;
    overdraftLimit:      number;
}
