// Generated by https://quicktype.io

export interface MakeDepositResponse {
    amount:                           number;
    bookingDate:                      string;
    externalId:                       string;
    holdExternalReferenceId:          string;
    notes:                            string;
    paymentOrderId:                   string;
    skipMaximumBalanceValidation:     boolean;
    transactionDetails:               any;
    valueDate:                        string;
}



