// Generated by https://quicktype.io

export interface TransferResponse {
    amount:          number;
    externalId:      string;
    notes:           string;
    paymentOrderId:  string;
    transferDetails: TransferDetails;
    valueDate:       string;
}

export interface TransferDetails {
    linkedAccountId:   string;
    linkedAccountKey:  string;
    linkedAccountType: string;
}
